name:                telltale

default-extensions:
- GeneralizedNewtypeDeriving
- NoImplicitPrelude
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- classy-prelude
- katip
- monad-logger

library:
  source-dirs: src

executables:
  telltale-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telltale

tests:
  telltale-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telltale
