name:                telltale


dependencies:
  - base >= 4.7 && < 5
  - rio

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

library:
  source-dirs: src
  default-extensions:
    - GeneralizedNewtypeDeriving
    - NoImplicitPrelude
    - OverloadedStrings
    - TypeOperators
    - DataKinds
  dependencies:
    - base >= 4.7 && < 5
    - rio
    - wai
    - http-types
    - warp
    - hedis
    - wai-websockets
    - websockets
    - servant
    - servant-server
    - monad-logger
    - mtl
    - katip

executables:
  telltale-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telltale

tests:
  telltale-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telltale
