name:                telltale


dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  default-extensions:
    - GeneralizedNewtypeDeriving
    - NoImplicitPrelude
    - OverloadedStrings
    - TypeOperators
    - FlexibleContexts
    - DataKinds
    - RecordWildCards
  dependencies:
    - base >= 4.7 && < 5
    - rio
    - aeson
    - aeson-casing
    - yaml
    - wai
    - http-types
    - warp
    - hedis
    - wai-websockets
    - websockets
    - servant
    - servant-server
    - monad-logger
    - mtl
    - katip

executables:
  telltale-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telltale

